# 调试模式
DEBUG_MODE: false

# FastAPI配置
fastapi:
  name: "zhaojin"
  version: "1.0.0"
  description: "招金培训系统后端 API 文档"
  summary: "招金培训系统后端 API 文档"
  debug: false
  host: "0.0.0.0"
  port: 8000
  root_path: ""

# API配置
API_V1_STR: "/v1"

# JWT配置
SECRET_KEY: "your-secret-key-here"
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 43200  # 30天

# 数据库配置
POSTGRES_HOST: "localhost"
POSTGRES_PORT: 5432
POSTGRES_DB: "zhaojin"
POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "postgres"

# 日志配置
logger:
  level: "INFO"
  name: "zhaojin"
  file_logger:
    path: "logs/zhaojin.log"
  stream_logger:
    type: "STDOUT"
  file_access_logger:
    path: "logs/access.log"

# CORS配置
BACKEND_CORS_ORIGINS: ["*"] 