# 调试模式
DEBUG_MODE: false

# FastAPI配置
fastapi:
  name: "zhaojin"
  version: "1.0.0"
  description: "招金培训系统后端 API 文档"
  summary: "招金培训系统后端 API 文档"
  debug: false
  host: "0.0.0.0"
  port: 8000
  root_path: ""
  # API文档配置
  swagger: true
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"
  openapi_prefix: ""
  cors:
    enable: true
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]
    max_age: 600

# API配置
API_V1_STR: "/v1"

# JWT配置
SECRET_KEY: "your-secret-key-here"
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 43200  # 30天

# 数据库配置
postgres:
  host: "localhost"
  port: 5432
  db: "zhaojin"
  user: "postgres"
  password: "postgres"

# 日志配置
logger:
  level: "INFO"
  name: "zhaojin"
  file_logger:
    path: "logs/zhaojin.log"
  stream_logger:
    type: "STDOUT"
  file_access_logger:
    path: "logs/access.log"

# CORS配置
BACKEND_CORS_ORIGINS: ["*"] 